#!/bin/bash

# ============================================================
# LinuxOps Enterprise Server
# File: scripts/scanner/report.sh
# Description:
# Generates a detailed network security report using Nmap
# ============================================================

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
REPORT_DIR="$PROJECT_ROOT/reports"
LOG_DIR="$PROJECT_ROOT/logs"

mkdir -p "$REPORT_DIR"
mkdir -p "$LOG_DIR"

REPORT_FILE="$REPORT_DIR/security-report.txt"
LOG_FILE="$LOG_DIR/server.log"

clear

echo "==============================================="
echo " LinuxOps Enterprise Server"
echo " Security Scan Report Generator"
echo "==============================================="
echo

# -------------------------------------------------------------
# Check Nmap
# -------------------------------------------------------------
if ! command -v nmap >/dev/null 2>&1; then
    echo "Nmap is not installed."
    echo "Install using:"
    echo
    echo "sudo apt install nmap -y"
    exit 1
fi

# -------------------------------------------------------------
# Ask Target
# -------------------------------------------------------------
read -rp "Enter IP Address or Hostname (default: localhost): " TARGET

TARGET=${TARGET:-localhost}

echo
echo "Target: $TARGET"
echo

echo "Choose Scan Type"
echo "--------------------------------"
echo "1. Quick Scan"
echo "2. Full Port Scan"
echo "3. Service Detection"
echo "4. OS Detection"
echo "5. Aggressive Scan"
echo

read -rp "Option: " OPTION

case $OPTION in

1)

SCAN="nmap $TARGET"

;;

2)

SCAN="nmap -p- $TARGET"

;;

3)

SCAN="nmap -sV $TARGET"

;;

4)

SCAN="sudo nmap -O $TARGET"

;;

5)

SCAN="sudo nmap -A $TARGET"

;;

*)

echo "Invalid Option"
exit 1

;;

esac

echo
echo "Scanning..."
echo

START_TIME=$(date)

{
echo "==========================================================="
echo "LinuxOps Enterprise Server"
echo "Security Scan Report"
echo "==========================================================="
echo
echo "Date        : $(date)"
echo "Target      : $TARGET"
echo "Hostname    : $(hostname)"
echo "Generated By: $(whoami)"
echo
echo "==========================================================="
echo

eval "$SCAN"

echo
echo "==========================================================="
echo
echo "System Information"
echo
echo "Hostname : $(hostname)"
echo "Kernel   : $(uname -r)"
echo "OS       : $(grep PRETTY_NAME /etc/os-release | cut -d= -f2 | tr -d '\"')"
echo "Uptime   : $(uptime -p)"
echo

echo "==========================================================="
echo
echo "Open Listening Ports"
echo

ss -tuln

echo
echo "==========================================================="
echo
echo "Firewall Status"
echo

if command -v ufw >/dev/null 2>&1
then
    sudo ufw status
else
    echo "UFW Not Installed"
fi

echo
echo "==========================================================="
echo
echo "Running Services"
echo

systemctl --type=service --state=running

echo
echo "==========================================================="
echo
echo "Network Interfaces"
echo

ip addr

echo
echo "==========================================================="
echo
echo "Routing Table"
echo

ip route

echo
echo "==========================================================="
echo
echo "Disk Usage"
echo

df -h

echo
echo "==========================================================="
echo
echo "Memory Usage"
echo

free -h

echo
echo "==========================================================="
echo
echo "CPU Load"
echo

uptime

echo
echo "==========================================================="
echo
echo "Top Processes"
echo

ps -eo pid,user,%cpu,%mem,command --sort=-%cpu | head -15

echo
echo "==========================================================="
echo
echo "Report Completed Successfully"

} > "$REPORT_FILE"

END_TIME=$(date)

echo "[$END_TIME] Security report generated for $TARGET" >> "$LOG_FILE"

echo
echo "==============================================="
echo "Report Generated Successfully"
echo "==============================================="
echo
echo "Report Location:"
echo "$REPORT_FILE"
echo
echo "Log File:"
echo "$LOG_FILE"
echo

echo "Preview"
echo "---------------------------------------"

head -30 "$REPORT_FILE"

echo
echo "Done."